AWSTemplateFormatVersion: "2010-09-09"
Description: dynamdb tables for common uses

Parameters:

Resources:
  TenantDetailsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: tenantName
          AttributeType: S
        - AttributeName: authCode
          AttributeType: S
        - AttributeName: subDomain
          AttributeType: S  
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: TenantConfig
          KeySchema:
            - AttributeName: tenantName
              KeyType: HASH
          Projection:
            NonKeyAttributes: 
              - userPoolId
              - appClientId
              - apiGatewayUrl
              - contractCount
              - status
              - authCode
              - subDomain
            ProjectionType: INCLUDE
        - IndexName: AuthCodeIndex
          KeySchema:
            - AttributeName: authCode
              KeyType: HASH
          Projection:
            NonKeyAttributes:
              - userPoolId
              - appClientId
              - apiGatewayUrl
            ProjectionType: INCLUDE
        - IndexName: SubDomainIndex
          KeySchema:
            - AttributeName: subDomain
              KeyType: HASH
          Projection:
            NonKeyAttributes:
              - userPoolId
              - appClientId
              - apiGatewayUrl
            ProjectionType: INCLUDE
      TableName: tenant-details

#  TenantUserMappingTable:
#    Type: AWS::DynamoDB::Table
#    Properties:
#      AttributeDefinitions:
#        - AttributeName: tenantId
#          AttributeType: S
#        - AttributeName: userName
#          AttributeType: S
#      KeySchema:
#        - AttributeName: tenantId
#          KeyType: HASH
#        - AttributeName: userName
#          KeyType: RANGE
#      BillingMode: PAY_PER_REQUEST 
#      TableName: ServerlessSaaS-TenantUserMapping
#      GlobalSecondaryIndexes: 
#        - IndexName: UserName
#          KeySchema: 
#            - AttributeName: userName
#              KeyType: HASH
#            - AttributeName: tenantId
#              KeyType: RANGE
#          Projection:
#            ProjectionType: ALL
Outputs:
  TenantDetailsTableArn: 
    Value: !GetAtt TenantDetailsTable.Arn
    Export:
      Name: TenantDetailsTableArn
  TenantDetailsTableName: 
    Value: !Ref TenantDetailsTable
    Export:
      Name: TenantDetailsTableName
#  TenantUserMappingTableArn: 
#    Value: !GetAtt TenantUserMappingTable.Arn
#  TenantUserMappingTableName: 
#    Value: !Ref TenantUserMappingTable