AWSTemplateFormatVersion: 2010-09-09
Description: S3 + CloudFront + Route53 A Record(Operations site)

Parameters:
  DomainName:
    Type: String
  HostedZoneId:
    Type: String
  CertificateArn:
    Type: String

Resources:
  OperationsSiteCloudFrontDistributionLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: operations-site-cf-log-bucket
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerPreferred
      #AccessControl: LogDeliveryWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: AutoDelete
            Status: Enabled
            ExpirationInDays: 15

  OperationsSiteBucket:
    Type: AWS::S3::Bucket
    #DeletionPolicy: Retain
    Properties:
      BucketName: operations-site-bucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  OperationsSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref OperationsSiteBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${OperationsSiteBucket}/*
            Principal:
              Service: cloudfront.amazonaws.com
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${OperationsSiteCloudFrontDistribution}
          #- Action: s3:ListBucket
          #  Effect: Allow
          #  Resource: !Sub arn:aws:s3:::${OperationsSiteBucket}
          #  Principal:
          #    Service: cloudfront.amazonaws.com
          #  Condition:
          #    StringEquals:
          #      AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${OperationsSiteCloudFrontDistribution}

  OperationsSiteCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub round-operations.${DomainName}
        PriceClass: PriceClass_200
        Origins:
          - Id: OperationsSiteOrigin
            DomainName: !Sub ${OperationsSiteBucket}.s3.${AWS::Region}.amazonaws.com
            OriginAccessControlId: !GetAtt OACOperationsSite.Id
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: index.html
        Logging:
          IncludeCookies: false
          Bucket: !Sub ${OperationsSiteCloudFrontDistributionLogBucket}.s3.${AWS::Region}.amazonaws.com
        Comment: !Sub operations-site-distribution
        DefaultCacheBehavior:
          TargetOriginId: OperationsSiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          ForwardedValues:
            QueryString: false
        CacheBehaviors:
          - PathPattern: "/assets/*"
            TargetOriginId: OperationsSiteOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            DefaultTTL: 86400
            MaxTTL: 31536000
            MinTTL: 0
            ForwardedValues:
              QueryString: false
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        IPV6Enabled: false
 
  OACOperationsSite:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: !Sub operations-site-oac
        Name: !Sub operations-site-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  
  Route53OperationsSiteRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub round-operations.${DomainName}
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 #　CloudFront Hosted Zone ID (固定値)
        DNSName: !GetAtt OperationsSiteCloudFrontDistribution.DomainName
Outputs:
  OperationsSiteCloudFrontDistributionDomain:
    Value: !GetAtt OperationsSiteCloudFrontDistribution.DomainName
    Description: CloudFront Domain Name
    Export:
      Name: Operations-Site-CloudFrontDomainName