/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/globals/AppFooter.vue')['default']
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseDataTable: typeof import('./components/base/BaseDataTable.vue')['default']
    BaseTextField: typeof import('./components/base/BaseTextField.vue')['default']
    BreadCrumbsAppBar: typeof import('./components/globals/appBar/BreadCrumbsAppBar.vue')['default']
    ChangePasswordForm: typeof import('./components/new_password/ChangePasswordForm.vue')['default']
    CreateButton: typeof import('./components/globals/button/CreateButton.vue')['default']
    CSVExportButton: typeof import('./components/globals/button/CSVExportButton.vue')['default']
    DefaultBreadcrumbs: typeof import('./components/globals/breadcrumbs/DefaultBreadcrumbs.vue')['default']
    DetailButton: typeof import('./components/globals/button/DetailButton.vue')['default']
    DomeinNameTextField: typeof import('./components/globals/textField/SubDomeinNameTextField.vue')['default']
    InformationNabigationDrower: typeof import('./components/globals/navigationDrawer/InformationNabigationDrower.vue')['default']
    LoginForm: typeof import('./components/login/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterNavigationDrower: typeof import('./components/globals/navigationDrawer/RouterNavigationDrower.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SubDomeinNameTextField: typeof import('./components/globals/textField/SubDomeinNameTextField.vue')['default']
    SubmitButton: typeof import('./components/globals/button/SubmitButton.vue')['default']
    TenantCreate: typeof import('./components/tenants/TenantCreate.vue')['default']
    TenantData: typeof import('./components/tenants/TenantData.vue')['default']
    TenantDetailCard: typeof import('./components/tenants/TenantDetailCard.vue')['default']
    Test: typeof import('./components/tenants/Test.vue')['default']
    TestButton: typeof import('./components/globals/button/TestButton.vue')['default']
    TopAppBar: typeof import('./components/globals/appBar/TopAppBar.vue')['default']
  }
}
