AWSTemplateFormatVersion: 2010-09-09
Description: S3 + CloudFront + Route53 A Record(Admin site)

Parameters:
  Env:
    Type: String
    Default: dev
  AppName:
    Type: String
    Default: test-attendance
  DomainName:
    Type: String
  HostedZoneId:
    Type: String
  CertificateArn:
    Type: String

Resources:
  AdminSiteCloudFrontDistributionLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Env}-${AppName}-admin-site-cf-log-bucket
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerPreferred
      #AccessControl: LogDeliveryWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: AutoDelete
            Status: Enabled
            ExpirationInDays: 15

  AdminSiteBucket:
    Type: AWS::S3::Bucket
    #DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${Env}-${AppName}-admin-site-bucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  AdminSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AdminSiteBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${AdminSiteBucket}/*
            Principal:
              Service: cloudfront.amazonaws.com
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${AdminSiteCloudFrontDistribution}
          #- Action: s3:ListBucket
          #  Effect: Allow
          #  Resource: !Sub arn:aws:s3:::${AdminSiteBucket}
          #  Principal:
          #    Service: cloudfront.amazonaws.com
          #  Condition:
          #    StringEquals:
          #      AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${AdminSiteCloudFrontDistribution}

  AdminSiteCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub roundadmin.${DomainName}
        PriceClass: PriceClass_200
        Origins:
          - Id: AdminSiteOrigin
            DomainName: !Sub ${AdminSiteBucket}.s3.${AWS::Region}.amazonaws.com
            OriginAccessControlId: !GetAtt OACAdminSite.Id
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: index.html
        Logging:
          IncludeCookies: false
          Bucket: !Ref AdminSiteCloudFrontDistributionLogBucket
          Prefix: !Sub ${Env}-${AppName}-admin-site-distribution/
        Comment: !Sub ${Env}-${AppName}-admin-site-distribution
        DefaultCacheBehavior:
          TargetOriginId: AdminSiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          ForwardedValues:
            QueryString: false
        CacheBehaviors:
          - PathPattern: "/assets/*"
            TargetOriginId: AdminSiteOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            DefaultTTL: 86400
            MaxTTL: 31536000
            MinTTL: 0
            ForwardedValues:
              QueryString: false
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        IPV6Enabled: false
 
  OACAdminSite:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: !Sub ${Env}-${AppName}-admin-site-oac
        Name: !Sub ${Env}-${AppName}-admin-site-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub roundadmin.${DomainName}
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 #　CloudFront Hosted Zone ID (固定値)
        DNSName: !GetAtt AdminSiteCloudFrontDistribution.DomainName

Outputs:
  AdminSiteCloudFrontDistributionDomain:
    Value: !GetAtt AdminSiteCloudFrontDistribution.DomainName
    Description: CloudFront Domain Name
    Export:
      Name: Admin-Site-CloudFrontDomainName