AWSTemplateFormatVersion: 2010-09-09
Description: "Cognito User Pool for Operations"

Parameters:
  DomainName:
    Type: String

Resources:
  CognitoOperationsUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !Sub operations-user-pool
      AutoVerifiedAttributes:
        - "email"
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:      
        InviteMessageTemplate:
          EmailMessage: !Join           
            - ""
            - - "Login into operations UI application at "
              - "<br>"
              - "https://"
              - "round-operations."
              - !Ref DomainName
              - "/"
              - "<br><br>"
              - "Username: {username}"
              - "<br>"
              - "Temporary password: {####}"
          EmailSubject: !Join 
            - ""
            - - "Your temporary password for operations UI application"
      Schema:
        - AttributeDataType: "String"
          Name: email
          Required: true
          Mutable: true
        - AttributeDataType: "String"
          Name: tenantId
        - AttributeDataType: "String"
          Name: userRole
          Required: false
          Mutable: true
      MfaConfiguration: "OPTIONAL"
      EnabledMfas: 
        - SOFTWARE_TOKEN_MFA #TOTPを有効化
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
        
  CognitoOperationsUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: !Sub operations-pool-client
      UserPoolId: !Ref CognitoOperationsUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - "ALLOW_USER_PASSWORD_AUTH"
        - "ALLOW_REFRESH_TOKEN_AUTH"
        - "ALLOW_USER_SRP_AUTH"
      PreventUserExistenceErrors: ENABLED
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - !Join ["",["https://round-operations.", !Ref DomainName, "/"]]
      LogoutURLs:  
        - !Join ["",["https://round-operations.", !Ref DomainName, "/"]]
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      ReadAttributes:
        - "custom:userRole"

#      WriteAttributes:
#        - "email"
#        - "custom:userRole"

#  CognitoOperationsGroup:
#    Type: AWS::Cognito::UserPoolGroup
#    Properties:
#      GroupName: SystemAdmins
#      Description: Admin user group
#      Precedence: 0
#      UserPoolId: !Ref CognitoOperationsUserPool

Outputs:
  CognitoOperationsUserPoolId:
    Description: "Operations User Pool ID"
    Value: !Ref CognitoOperationsUserPool
    Export:
      Name: Operations-UserPoolId
  CognitoOperationsUserPoolClientId:
    Description: "Operations User Pool Client ID"
    Value: !Ref CognitoOperationsUserPoolClient
    Export:
      Name: Operations-UserPoolClientId