AWSTemplateFormatVersion: 2010-09-09
Description: "Cognito User Pool for Operations"

Parameters:
  DomainName:
    Type: String

Resources:
  CognitoOperationsUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: operations-user-pool
      UsernameConfiguration:
        CaseSensitive: true # ユーザー名の大文字小文字を区別
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: admin_only # 管理者のみパスワードリセット可能
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true # 管理者のみユーザー作成可能
        InviteMessageTemplate:
          EmailMessage: !Join
            - ""
            - - "Login into operations UI application at "
              - "<br>"
              - "https://"
              - "round-operations."
              - !Ref DomainName
              - "/"
              - "<br><br>"
              - "Username: {username}"
              - "<br>"
              - "Temporary password: {####}"
          EmailSubject: !Join 
            - ""
            - - "Your temporary password for operations UI application"
      Schema:
        - AttributeDataType: "String"
          Name: email
          Required: true
          Mutable: true
        - AttributeDataType: "String"
          Name: userRole
          Mutable: true
      MfaConfiguration: "OPTIONAL"
      EnabledMfas: 
        - SOFTWARE_TOKEN_MFA #TOTPを有効化
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
        
  CognitoOperationsUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: operations-pool-client
      UserPoolId: !Ref CognitoOperationsUserPool
      GenerateSecret: false # シークレット不要
      ExplicitAuthFlows:
        - "ALLOW_USER_PASSWORD_AUTH"
        - "ALLOW_REFRESH_TOKEN_AUTH"
        - "ALLOW_USER_SRP_AUTH"
      PreventUserExistenceErrors: ENABLED # ユーザーが存在しない場合、エラーメッセージを曖昧
      ReadAttributes:
        - "custom:userRole"

Outputs:
  CognitoOperationsUserPoolId:
    Description: "Operations User Pool ID"
    Value: !Ref CognitoOperationsUserPool
    Export:
      Name: Operations-UserPoolId
  CognitoOperationsUserPoolClientId:
    Description: "Operations User Pool Client ID"
    Value: !Ref CognitoOperationsUserPoolClient
    Export:
      Name: Operations-UserPoolClientId