AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: "User Interface Resources for Operations Site"

Parameters:
  AppName:
    Type: String
  DomainName:
    Type: String
  HostedZoneId:
    Type: String
  CertificateArn:
    Type: String
  Env:
    Type: String

Resources:
  OperationsSiteCloudFrontDistributionLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AppName}-operations-site-cf-log-bucket
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerPreferred
      #AccessControl: LogDeliveryWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: AutoDelete
            Status: Enabled
            ExpirationInDays: 15

##################################################################################
## 管理者サイト用 S3バケット
##################################################################################
  OperationsSiteBucket:
    Type: AWS::S3::Bucket
    #DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${AppName}-operations-site-bucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  OperationsSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: OperationsSiteBucket
    Properties:
      Bucket: !Ref OperationsSiteBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${OperationsSiteBucket}/*
            Principal:
              Service: cloudfront.amazonaws.com
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${OperationsSiteCloudFrontDistribution}


###################################################################################
## 管理者サイト用 CloudFront ディストリビューション
###################################################################################
  OACOperationsSite:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: operations-site-oac
        Name: operations-site-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  OperationsSiteCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - OperationsSiteBucket
      - OACOperationsSite
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub operations-site-distribution
        Aliases:
          - !Sub round-operations.${DomainName}
        PriceClass: PriceClass_200
        Origins:
          - Id: OperationsSiteOrigin
            DomainName: !Sub ${OperationsSiteBucket}.s3.amazonaws.com
            OriginAccessControlId: !GetAtt OACOperationsSite.Id
            S3OriginConfig: {}
          - Id: ApiGatewayOrigin
            DomainName: !Sub 
              - "${OperationsHttpApiId}.execute-api.${AWS::Region}.amazonaws.com"
              - { OperationsHttpApiId: !ImportValue Operations-HttpApiId }
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        Logging:
          IncludeCookies: false
          Bucket: !Sub ${OperationsSiteCloudFrontDistributionLogBucket}.s3.${AWS::Region}.amazonaws.com
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: OperationsSiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          OriginRequestPolicyId: 59781a5b-3903-41f3-afcb-af62929ccde1 # CORS-CustomOrigin
          Compress: true
        CacheBehaviors:
          - PathPattern: "/assets/*"
            TargetOriginId: OperationsSiteOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
            OriginRequestPolicyId: 59781a5b-3903-41f3-afcb-af62929ccde1 # CORS-CustomOrigin
            Compress: true
          - PathPattern: !Sub "/api/*"
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac # AllViewerExceptHostHeader　カスタムポリシーにするか検討
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        IPV6Enabled: false
        HttpVersion: http2

################################################################################
## 管理者サイト用 Route53 レコードセット
################################################################################
  Route53OperationsSiteRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub round-operations.${DomainName}
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 #　CloudFront Hosted Zone ID (固定値)
        DNSName: !GetAtt OperationsSiteCloudFrontDistribution.DomainName

Outputs:
  OperationsSiteCloudFrontDistributionDomain:
    Value: !GetAtt OperationsSiteCloudFrontDistribution.DomainName
    Description: CloudFront Domain Name
    Export:
      Name: Operations-Site-CloudFrontDomainName