AWSTemplateFormatVersion: 2010-09-09
Description: "User Interface Resources for User Site"

Parameters:
  AppName:
    Type: String
  DomainName:
    Type: String
  CertificateArn:
    Type: String

Resources:
  #UserSiteCloudFrontDistributionLogBucket:
  #  Type: AWS::S3::Bucket
  #  Properties:
  #    BucketName: !Sub ${AppName}-user-site-cf-log-bucket
  #    OwnershipControls:
  #      Rules:
  #      - ObjectOwnership: BucketOwnerPreferred
  #    #AccessControl: LogDeliveryWrite
  #    PublicAccessBlockConfiguration:
  #      BlockPublicAcls: true
  #      BlockPublicPolicy: true
  #      IgnorePublicAcls: true
  #      RestrictPublicBuckets: true
  #    LifecycleConfiguration:
  #      Rules:
  #        - Id: AutoDelete
  #          Status: Enabled
  #          ExpirationInDays: 15

  UserSiteBucket:
    Type: AWS::S3::Bucket
    #DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${AppName}-user-site-bucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  UserSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UserSiteBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${UserSiteBucket}/*
            Principal:
              Service: cloudfront.amazonaws.com
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${UserSiteCloudFrontDistribution}
          #- Action: s3:ListBucket
          #  Effect: Allow
          #  Resource: !Sub arn:aws:s3:::${UserSiteBucket}
          #  Principal:
          #    Service: cloudfront.amazonaws.com
          #  Condition:
          #    StringEquals:
          #      AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${UserSiteCloudFrontDistribution}

  UserSiteCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "*.${DomainName}"
        PriceClass: PriceClass_200
        Origins:
          - Id: UserSiteOrigin
            DomainName: !Sub ${UserSiteBucket}.s3.${AWS::Region}.amazonaws.com
            OriginAccessControlId: !GetAtt OACUserSite.Id
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: index.html
        #Logging:
        #  IncludeCookies: false
        #  Bucket: !Sub ${UserSiteCloudFrontDistributionLogBucket}.s3.${AWS::Region}.amazonaws.com
        #Comment: user-site-distribution
        DefaultCacheBehavior:
          TargetOriginId: UserSiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled
        CacheBehaviors:
          - PathPattern: "/assets/*"
            TargetOriginId: UserSiteOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        IPV6Enabled: false
        HttpVersion: http2
 
  OACUserSite:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: user-site-oac
        Name: user-site-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

Outputs:
  UserSiteCloudFrontDistributionDomain:
    Value: !GetAtt UserSiteCloudFrontDistribution.DomainName
    Description: CloudFront Domain Name
    Export:
      Name: User-Site-CloudFrontDomainName