AWSTemplateFormatVersion: 2010-09-09
Description: S3 + CloudFront + Route53 A Record(user admin site)

Parameters:
  Env:
    Type: String
    Default: dev
  AppName:
    Type: String
    Default: test-attendance
  DomainName:
    Type: String
  HostedZoneId:
    Type: String
  CertificateArn:
    Type: String

Resources:
  UserAdminSiteCloudFrontDistributionLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Env}-${AppName}-user-admin-site-cf-log-bucket
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerPreferred
      #AccessControl: LogDeliveryWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: AutoDelete
            Status: Enabled
            ExpirationInDays: 15

  UserAdminSiteBucket:
    Type: AWS::S3::Bucket
    #DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${Env}-${AppName}-user-admin-site-bucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  UserAdminSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UserAdminSiteBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${UserAdminSiteBucket}/*
            Principal:
              Service: cloudfront.amazonaws.com
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${UserAdminSiteCloudFrontDistribution}
          #- Action: s3:ListBucket
          #  Effect: Allow
          #  Resource: !Sub arn:aws:s3:::${UserAdminSiteBucket}
          #  Principal:
          #    Service: cloudfront.amazonaws.com
          #  Condition:
          #    StringEquals:
          #      AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${UserAdminSiteCloudFrontDistribution}

  UserAdminSiteCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "*.${DomainName}"
        PriceClass: PriceClass_200
        Origins:
          - Id: UserAdminSiteOrigin
            DomainName: !Sub ${UserAdminSiteBucket}.s3.${AWS::Region}.amazonaws.com
            OriginAccessControlId: !GetAtt OACUserAdminSite.Id
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: index.html
        Logging:
          IncludeCookies: false
          Bucket: !Sub ${UserAdminSiteCloudFrontDistributionLogBucket}.s3.${AWS::Region}.amazonaws.com
          Prefix: !Sub ${Env}-${AppName}-user-admin-site-distribution/
        Comment: !Sub ${Env}-${AppName}-user-admin-site-distribution
        DefaultCacheBehavior:
          TargetOriginId: UserAdminSiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          ForwardedValues:
            QueryString: false
        CacheBehaviors:
          - PathPattern: "/assets/*"
            TargetOriginId: UserAdminSiteOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            DefaultTTL: 86400
            MaxTTL: 31536000
            MinTTL: 0
            ForwardedValues:
              QueryString: false
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        IPV6Enabled: false
 
  OACUserAdminSite:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: !Sub ${Env}-${AppName}-user-admin-site-oac
        Name: !Sub ${Env}-${AppName}-user-admin-site-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

Outputs:
  UserAdminSiteCloudFrontDistributionDomain:
    Value: !GetAtt UserAdminSiteCloudFrontDistribution.DomainName
    Description: CloudFront Domain Name
    Export:
      Name: User-Admin-Site-CloudFrontDomainName