AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Functions for Tenants Site

Globals:
  Function:
    Runtime: nodejs22.x
    MemorySize: 256
    Timeout: 30
    Environment:
      Variables:
        NODE_OPTIONS: "--enable-source-maps"

Resources:
###################################################################################
## テナントサイト用 API Gateway(HTTP API) ＆ Lambda Authorizer
###################################################################################
  TenantsHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: api
      Name: tenants-http-api
#      CorsConfiguration:
#        AllowMethods:
#          - GET
#          - DELETE
#          - OPTIONS
#        AllowHeaders:
#          - Content-Type
#          - Authorization
#        AllowOrigins:
#          - "*"
      Auth:
        DefaultAuthorizer: TenantsLambdaAuthorizer
        Authorizers:
          TenantsLambdaAuthorizer:
            AuthorizerPayloadFormatVersion: 2.0
            FunctionArn: !GetAtt TenantsAuthorizerFunction.Arn
            EnableSimpleResponses: true
            EnableFunctionDefaultPermissions: true
            Identity:
              Headers: 
                - Authorization
              ReauthorizeEvery: 900 # 15分キャッシュ

  TenantsAuthorizerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: tenants-authorizer-execution-role
      Path: '/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: tenants-authorizer-execution-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:List*
                Resource: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*

  TenantsAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tenants-authorizer-function
      CodeUri: ../../backend/authorizer/tenants/dist
      Handler: index.handler
      Role: !GetAtt TenantsAuthorizerExecutionRole.Arn
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          TENANTS_REGION: !Ref "AWS::Region"

  TenantsAuthorizerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${TenantsAuthorizerFunction}
      RetentionInDays: 14

###################################################################################
## テナントサイト用 Tenants Service Lambda Function
###################################################################################
  TenantsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: tenants-execution-role
      Path: '/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
#      Policies:
#        - PolicyName: tenants-execution-policy
#          PolicyDocument:
#            Version: 2012-10-17
#            Statement:
#              - Effect: Allow
#                Action:
#                  - cognito-idp:List*
#                Resource: arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*

  TenantsUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tenants-users-function
      CodeUri: ../../backend/tenants/users_service/dist
      Handler: index.handler
      Role: !GetAtt TenantsExecutionRole.Arn
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref TenantsHttpApi
            Path: /users/{proxy+}
            Method: ANY
            PayloadFormatVersion: "2.0"

  TenantsUsersFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${TenantsUsersFunction}
      RetentionInDays: 14

Outputs:
  TenantsHttpApiId:
    Value: !Ref TenantsHttpApi
    Description: Tenants HTTP API ID
    Export:
      Name: Tenants-HttpApiId