AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Functions for Operations Site

Globals:
  Function:
    Runtime: nodejs24.x
    MemorySize: 256
    Timeout: 30
    Environment:
      Variables:
        NODE_OPTIONS: "--enable-source-maps"

Resources:
###################################################################################
## 管理者サイト用 API Gateway(HTTP API) ＆ Lambda Authorizer
###################################################################################
  OperationsHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: api
      Name: operations-http-api
#      CorsConfiguration:
#        AllowMethods:
#          - GET
#          - DELETE
#          - OPTIONS
#        AllowHeaders:
#          - Content-Type
#          - Authorization
#        AllowOrigins:
#          - "*"
      Auth:
        DefaultAuthorizer: OperationsLambdaAuthorizer
        Authorizers:
          OperationsLambdaAuthorizer:
            AuthorizerPayloadFormatVersion: 2.0
            FunctionArn: !GetAtt OperationsAuthorizerFunction.Arn
            EnableSimpleResponses: true
            EnableFunctionDefaultPermissions: true
            Identity:
              Headers: 
                - Authorization
              ReauthorizeEvery: 900 # 15分キャッシュ

  OperationsAuthorizerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: operations-authorizer-execution-role
      Path: '/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: operations-authorizer-execution-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:List*
                Resource: !Sub
                  - arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${OperationsUsersUserPool}
                  - { OperationsUsersUserPool: !ImportValue Operations-UserPoolId }

  OperationsAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: operations-authorizer-function
      CodeUri: ../../backend/authorizer/operations/dist
      Handler: index.handler
      Role: !GetAtt OperationsAuthorizerExecutionRole.Arn
      MemorySize: 256
      Timeout: 5
      Environment:
        Variables:
          OPERATIONS_REGION: !Ref "AWS::Region"
          OPERATIONS_USERS_USER_POOL: !ImportValue Operations-UserPoolId
          OPERATIONS_USERS_APP_CLIENT: !ImportValue Operations-UserPoolClientId

  OperationsAuthorizerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${OperationsAuthorizerFunction}
      RetentionInDays: 14

###################################################################################
## 管理者サイト用 Operations Service Lambda Function
###################################################################################
  OperationsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: operations-execution-role
      Path: '/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
#      Policies:
#        - PolicyName: operations-execution-policy
#          PolicyDocument:
#            Version: 2012-10-17
#            Statement:
#              - Effect: Allow
#                Action:
#                  - cognito-idp:List*
#                Resource: !Sub
#                  - arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${OperationsUserPool}
#                  - { OperationsUserPool: !ImportValue Operations-UserPoolId }

  OperationsUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: operations-users-function
      CodeUri: ../../backend/operations/users_service/dist
      Handler: index.handler
      Role: !GetAtt OperationsExecutionRole.Arn
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref OperationsHttpApi
            Path: /users/{proxy+}
            Method: ANY
            PayloadFormatVersion: "2.0"
  
  OperationsUsersFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${OperationsUsersFunction}
      RetentionInDays: 14

Outputs:
  OperationsHttpApiId:
    Value: !Ref OperationsHttpApi
    Description: Operations HTTP API ID
    Export:
      Name: Operations-HttpApiId