AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Functions for Operations Site

Globals:
  Function:
    Runtime: nodejs22.x
    MemorySize: 256
    Timeout: 30
    Environment:
      Variables:
        NODE_OPTIONS: "--enable-source-maps"

Resources:
  OperationsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: operations-execution-role
      Path: '/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: operations-authorizer-execution-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:List*
                Resource: !Sub
                  - arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${OperationsUsersUserPool}
                  - { OperationsUsersUserPool: !ImportValue Operations-UserPoolId }

  OperationsUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: operations-users-function
      CodeUri: ../../backend/operations/users_service/dist
      Handler: index.handler
      Role: !GetAtt OperationsExecutionRole.Arn
      Events:
        ProxyApi:
          Type: HttpApi
          Properties:
            ApiId: !ImportValue Operations-HttpApiId
            Path: /users/{proxy+} 
            Method: ANY
